[package]
name = "might_sleep"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["sleep"]
readme = "README.md"
description = "limit cpu usage by estimating sleep time"
repository = "https://github.com/TanTanDev/might_sleep.git"

[dependencies]
